'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'zh' | 'ja' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'dashboard.title': 'Dashboard',
    'dashboard.description': 'Welcome back! Here\'s what\'s happening.',
    'payments.title': 'Payments',
    'payments.description': 'Manage payments and transactions',
    'clients.title': 'All Clients',
    'clients.description': 'A list of all your clients and their information',
    'settings.title': 'Settings',
    'settings.description': 'Manage your application settings',
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'theme.system': 'System',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.italian': 'Italiano',
    'language.portuguese': 'Português',
    'language.chinese': '中文',
    'language.japanese': '日本語',
    'language.korean': '한국어',
    'button.add_client': 'Add Client',
    'button.process_payment': 'Process Payment',
    'button.filter': 'Filter',
    'button.export': 'Export',
    'button.save': 'Save',
    'button.cancel': 'Cancel',
    'button.edit': 'Edit',
    'button.delete': 'Delete',
    'button.view': 'View',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.completed': 'Completed',
  },
  es: {
    'dashboard.title': 'Panel de Control',
    'dashboard.description': '¡Bienvenido de vuelta! Esto es lo que está pasando.',
    'payments.title': 'Pagos',
    'payments.description': 'Gestiona pagos y transacciones',
    'clients.title': 'Todos los Clientes',
    'clients.description': 'Una lista de todos tus clientes y su información',
    'settings.title': 'Configuración',
    'settings.description': 'Gestiona la configuración de tu aplicación',
    'theme.light': 'Modo Claro',
    'theme.dark': 'Modo Oscuro',
    'theme.system': 'Sistema',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.italian': 'Italiano',
    'language.portuguese': 'Português',
    'language.chinese': '中文',
    'language.japanese': '日本語',
    'language.korean': '한국어',
    'button.add_client': 'Agregar Cliente',
    'button.process_payment': 'Procesar Pago',
    'button.filter': 'Filtrar',
    'button.export': 'Exportar',
    'button.save': 'Guardar',
    'button.cancel': 'Cancelar',
    'button.edit': 'Editar',
    'button.delete': 'Eliminar',
    'button.view': 'Ver',
    'status.active': 'Activo',
    'status.inactive': 'Inactivo',
    'status.pending': 'Pendiente',
    'status.completed': 'Completado',
  },
  fr: {
    'dashboard.title': 'Tableau de Bord',
    'dashboard.description': 'Bon retour ! Voici ce qui se passe.',
    'payments.title': 'Paiements',
    'payments.description': 'Gérez les paiements et transactions',
    'clients.title': 'Tous les Clients',
    'clients.description': 'Une liste de tous vos clients et leurs informations',
    'settings.title': 'Paramètres',
    'settings.description': 'Gérez les paramètres de votre application',
    'theme.light': 'Mode Clair',
    'theme.dark': 'Mode Sombre',
    'theme.system': 'Système',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.italian': 'Italiano',
    'language.portuguese': 'Português',
    'language.chinese': '中文',
    'language.japanese': '日本語',
    'language.korean': '한국어',
    'button.add_client': 'Ajouter Client',
    'button.process_payment': 'Traiter Paiement',
    'button.filter': 'Filtrer',
    'button.export': 'Exporter',
    'button.save': 'Enregistrer',
    'button.cancel': 'Annuler',
    'button.edit': 'Modifier',
    'button.delete': 'Supprimer',
    'button.view': 'Voir',
    'status.active': 'Actif',
    'status.inactive': 'Inactif',
    'status.pending': 'En Attente',
    'status.completed': 'Terminé',
  },
  // Add more languages as needed
  de: {
    'dashboard.title': 'Dashboard',
    'dashboard.description': 'Willkommen zurück! Hier ist was passiert.',
    'payments.title': 'Zahlungen',
    'payments.description': 'Zahlungen und Transaktionen verwalten',
    'clients.title': 'Alle Kunden',
    'clients.description': 'Eine Liste aller Ihrer Kunden und deren Informationen',
    'settings.title': 'Einstellungen',
    'settings.description': 'Verwalten Sie Ihre Anwendungseinstellungen',
    'theme.light': 'Heller Modus',
    'theme.dark': 'Dunkler Modus',
    'theme.system': 'System',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.italian': 'Italiano',
    'language.portuguese': 'Português',
    'language.chinese': '中文',
    'language.japanese': '日本語',
    'language.korean': '한국어',
    'button.add_client': 'Kunde Hinzufügen',
    'button.process_payment': 'Zahlung Verarbeiten',
    'button.filter': 'Filtern',
    'button.export': 'Exportieren',
    'button.save': 'Speichern',
    'button.cancel': 'Abbrechen',
    'button.edit': 'Bearbeiten',
    'button.delete': 'Löschen',
    'button.view': 'Anzeigen',
    'status.active': 'Aktiv',
    'status.inactive': 'Inaktiv',
    'status.pending': 'Ausstehend',
    'status.completed': 'Abgeschlossen',
  },
  it: {
    'dashboard.title': 'Dashboard',
    'dashboard.description': 'Bentornato! Ecco cosa sta succedendo.',
    'payments.title': 'Pagamenti',
    'payments.description': 'Gestisci pagamenti e transazioni',
    'clients.title': 'Tutti i Clienti',
    'clients.description': 'Un elenco di tutti i tuoi clienti e le loro informazioni',
    'settings.title': 'Impostazioni',
    'settings.description': 'Gestisci le impostazioni della tua applicazione',
    'theme.light': 'Modalità Chiara',
    'theme.dark': 'Modalità Scura',
    'theme.system': 'Sistema',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.italian': 'Italiano',
    'language.portuguese': 'Português',
    'language.chinese': '中文',
    'language.japanese': '日本語',
    'language.korean': '한국어',
    'button.add_client': 'Aggiungi Cliente',
    'button.process_payment': 'Elabora Pagamento',
    'button.filter': 'Filtra',
    'button.export': 'Esporta',
    'button.save': 'Salva',
    'button.cancel': 'Annulla',
    'button.edit': 'Modifica',
    'button.delete': 'Elimina',
    'button.view': 'Visualizza',
    'status.active': 'Attivo',
    'status.inactive': 'Inattivo',
    'status.pending': 'In Sospeso',
    'status.completed': 'Completato',
  },
  pt: {
    'dashboard.title': 'Painel de Controle',
    'dashboard.description': 'Bem-vindo de volta! Aqui está o que está acontecendo.',
    'payments.title': 'Pagamentos',
    'payments.description': 'Gerencie pagamentos e transações',
    'clients.title': 'Todos os Clientes',
    'clients.description': 'Uma lista de todos os seus clientes e suas informações',
    'settings.title': 'Configurações',
    'settings.description': 'Gerencie as configurações do seu aplicativo',
    'theme.light': 'Modo Claro',
    'theme.dark': 'Modo Escuro',
    'theme.system': 'Sistema',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.italian': 'Italiano',
    'language.portuguese': 'Português',
    'language.chinese': '中文',
    'language.japanese': '日本語',
    'language.korean': '한국어',
    'button.add_client': 'Adicionar Cliente',
    'button.process_payment': 'Processar Pagamento',
    'button.filter': 'Filtrar',
    'button.export': 'Exportar',
    'button.save': 'Salvar',
    'button.cancel': 'Cancelar',
    'button.edit': 'Editar',
    'button.delete': 'Excluir',
    'button.view': 'Visualizar',
    'status.active': 'Ativo',
    'status.inactive': 'Inativo',
    'status.pending': 'Pendente',
    'status.completed': 'Concluído',
  },
  zh: {
    'dashboard.title': '仪表板',
    'dashboard.description': '欢迎回来！这是正在发生的事情。',
    'payments.title': '付款',
    'payments.description': '管理付款和交易',
    'clients.title': '所有客户',
    'clients.description': '您所有客户及其信息的列表',
    'settings.title': '设置',
    'settings.description': '管理您的应用程序设置',
    'theme.light': '浅色模式',
    'theme.dark': '深色模式',
    'theme.system': '系统',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.italian': 'Italiano',
    'language.portuguese': 'Português',
    'language.chinese': '中文',
    'language.japanese': '日本語',
    'language.korean': '한국어',
    'button.add_client': '添加客户',
    'button.process_payment': '处理付款',
    'button.filter': '筛选',
    'button.export': '导出',
    'button.save': '保存',
    'button.cancel': '取消',
    'button.edit': '编辑',
    'button.delete': '删除',
    'button.view': '查看',
    'status.active': '活跃',
    'status.inactive': '非活跃',
    'status.pending': '待处理',
    'status.completed': '已完成',
  },
  ja: {
    'dashboard.title': 'ダッシュボード',
    'dashboard.description': 'おかえりなさい！ここで何が起こっているかです。',
    'payments.title': '支払い',
    'payments.description': '支払いと取引を管理',
    'clients.title': 'すべてのクライアント',
    'clients.description': 'すべてのクライアントとその情報のリスト',
    'settings.title': '設定',
    'settings.description': 'アプリケーション設定を管理',
    'theme.light': 'ライトモード',
    'theme.dark': 'ダークモード',
    'theme.system': 'システム',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.italian': 'Italiano',
    'language.portuguese': 'Português',
    'language.chinese': '中文',
    'language.japanese': '日本語',
    'language.korean': '한국어',
    'button.add_client': 'クライアント追加',
    'button.process_payment': '支払い処理',
    'button.filter': 'フィルター',
    'button.export': 'エクスポート',
    'button.save': '保存',
    'button.cancel': 'キャンセル',
    'button.edit': '編集',
    'button.delete': '削除',
    'button.view': '表示',
    'status.active': 'アクティブ',
    'status.inactive': '非アクティブ',
    'status.pending': '保留中',
    'status.completed': '完了',
  },
  ko: {
    'dashboard.title': '대시보드',
    'dashboard.description': '다시 오신 것을 환영합니다! 여기서 일어나고 있는 일입니다.',
    'payments.title': '결제',
    'payments.description': '결제 및 거래 관리',
    'clients.title': '모든 클라이언트',
    'clients.description': '모든 클라이언트와 그들의 정보 목록',
    'settings.title': '설정',
    'settings.description': '애플리케이션 설정 관리',
    'theme.light': '라이트 모드',
    'theme.dark': '다크 모드',
    'theme.system': '시스템',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.french': 'Français',
    'language.german': 'Deutsch',
    'language.italian': 'Italiano',
    'language.portuguese': 'Português',
    'language.chinese': '中文',
    'language.japanese': '日本語',
    'language.korean': '한국어',
    'button.add_client': '클라이언트 추가',
    'button.process_payment': '결제 처리',
    'button.filter': '필터',
    'button.export': '내보내기',
    'button.save': '저장',
    'button.cancel': '취소',
    'button.edit': '편집',
    'button.delete': '삭제',
    'button.view': '보기',
    'status.active': '활성',
    'status.inactive': '비활성',
    'status.pending': '대기 중',
    'status.completed': '완료',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Get language from localStorage or default to English
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
