'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'dashboard.title': 'Dashboard',
    'dashboard.description': 'Welcome back! Here\'s what\'s happening.',
    'payments.title': 'Payments',
    'payments.description': 'Manage payments and transactions',
    'clients.title': 'All Clients',
    'clients.description': 'A list of all your clients and their information',
    'settings.title': 'Settings',
    'settings.description': 'Manage your application settings',
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'theme.system': 'System',
    'language.english': 'English',
    'language.spanish': 'Español',
    'button.add_client': 'Add Client',
    'button.process_payment': 'Process Payment',
    'button.filter': 'Filter',
    'button.export': 'Export',
    'button.save': 'Save',
    'button.cancel': 'Cancel',
    'button.edit': 'Edit',
    'button.delete': 'Delete',
    'button.view': 'View',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'status.completed': 'Completed',
    // Common translations
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.sign_in': 'Sign In',
    'common.get_started': 'Get Started',
    // Home page translations
    'home.stats.active_users': 'Active Users',
    'home.stats.messages_sent': 'Messages Sent',
    'home.stats.payments_processed': 'Payments Processed',
    'home.stats.customer_satisfaction': 'Customer Satisfaction',
    'home.hero.title': 'Customer Communication Platform',
    'home.hero.description': 'Streamline your client relationships with our comprehensive communication and management platform.',
    'home.hero.get_started': 'Start Free Trial',
    'home.features.title': 'Everything you need to manage clients',
    'home.features.subtitle': 'Our platform provides all the tools you need to build and maintain strong client relationships.',
    'home.features.clients.title': 'Client Management',
    'home.features.clients.description': 'Complete client database with detailed profiles, interaction history, and relationship tracking.',
    'home.features.communication.title': 'Communication Hub',
    'home.features.communication.description': 'Unified messaging system with email, SMS, and in-app notifications for seamless client communication.',
    'home.features.payments.title': 'Payment Processing',
    'home.features.payments.description': 'Secure payment processing with multiple payment methods and automated invoicing.',
    'home.features.analytics.title': 'Investment Analytics',
    'home.features.analytics.description': 'Advanced analytics and reporting tools to track performance and make data-driven decisions.',
    'home.features.security.title': 'Security & Privacy',
    'home.features.security.description': 'Enterprise-grade security with role-based access control and data encryption.',
    'home.features.dashboard.title': 'Analytics Dashboard',
    'home.features.dashboard.description': 'Real-time insights and performance metrics to help you make informed decisions.',
    'home.demo.title': 'Demo Instructions',
    'home.demo.subtitle': 'This is a demo project showcasing the platform capabilities. Use the buttons below to test different user experiences.',
    'home.demo.admin.title': 'Admin Dashboard',
    'home.demo.admin.description': 'Experience the full admin interface with client management, analytics, and system controls.',
    'home.demo.admin.button': 'Login as Admin',
    'home.demo.client.title': 'Client Portal',
    'home.demo.client.description': 'See the client-facing interface with account management, payments, and communication features.',
    'home.demo.client.button': 'Login as Client',
    'home.demo.note': 'For full authentication flow, use the email addresses below with magic link authentication.',
    'home.footer.company': 'Company',
    'home.footer.product': 'Product',
    'home.footer.resources': 'Resources',
    'home.footer.legal': 'Legal',
    'home.footer.about': 'About Us',
    'home.footer.careers': 'Careers',
    'home.footer.contact': 'Contact',
    'home.footer.features': 'Features',
    'home.footer.pricing': 'Pricing',
    'home.footer.documentation': 'Documentation',
    'home.footer.support': 'Support',
    'home.footer.privacy': 'Privacy Policy',
    'home.footer.terms': 'Terms of Service',
    'home.footer.cookies': 'Cookie Policy',
    'home.footer.rights': 'All rights reserved.',
    // Login page translations
    'login.title': 'Sign In',
    'login.subtitle': 'Welcome back! Please sign in to your account.',
    'login.email.label': 'Email Address',
    'login.email.placeholder': 'Enter your email',
    'login.password.label': 'Password',
    'login.password.placeholder': 'Enter your password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.signin': 'Sign In',
    'login.or': 'Or continue with',
    'login.google': 'Continue with Google',
    'login.magic_link': 'Send Magic Link',
    'login.whatsapp': 'WhatsApp',
    'login.no_account': "Don't have an account?",
    'login.signup': 'Sign up',
    'login.demo.title': 'Demo Mode',
    'login.demo.description': 'Click the buttons below to test different user types:',
    'login.auth_info.title': 'Email Authentication',
    'login.auth_info.description': 'You can also test the authentication flow using these demo email addresses:',
    'login.auth_info.admin': 'Admin Dashboard',
    'login.auth_info.client': 'Client Portal',
    'login.auth_info.instruction': 'Enter either email above and click "Send Magic Link" to test the full authentication flow.',
    'login.method.email': 'Email',
    'login.method.whatsapp': 'WhatsApp',
    'login.whatsapp.title': 'WhatsApp Login',
    'login.whatsapp.description': 'Enter your phone number to receive a verification code via WhatsApp',
    'login.whatsapp.phone_label': 'Phone Number',
    'login.whatsapp.phone_placeholder': '(123) 456-7890',
    'login.whatsapp.code_description': 'We\'ll send a 6-digit code to this number via WhatsApp',
    'login.whatsapp.send_code': 'Send WhatsApp Code',
    'login.whatsapp.verify_code': 'Verification Code',
    'login.whatsapp.code_placeholder': '123456',
    'login.whatsapp.success_message': 'WhatsApp verification code sent!',
    'login.whatsapp.error_invalid_phone': 'Please enter a valid phone number',
    'login.whatsapp.error_invalid_code': 'Please enter the 6-digit verification code',
    'login.whatsapp.disclaimer': 'By continuing, you agree to receive messages via WhatsApp',
    'login.whatsapp.resend_code': 'Resend Code',
    'login.whatsapp.back_to_phone': 'Back to Phone Number',
    // Dashboard translations
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'Here\'s an overview of your account and recent activity.',
    'dashboard.recent_activity': 'Recent Activity',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.total_clients': 'Total Clients',
    'dashboard.active_payments': 'Active Payments',
    'dashboard.total_revenue': 'Total Revenue',
    'dashboard.pending_tasks': 'Pending Tasks',
    'dashboard.view_all': 'View All',
    'dashboard.add_client': 'Add Client',
    'dashboard.process_payment': 'Process Payment',
    'dashboard.send_message': 'Send Message',
    'dashboard.create_report': 'Create Report',
    'dashboard.active_conversations': 'Active Conversations',
    'dashboard.files_uploaded': 'Files Uploaded',
    'dashboard.recent_activity_desc': 'Latest updates from your clients',
    'dashboard.quick_actions_desc': 'Common tasks and shortcuts',
    'dashboard.manage_clients': 'Manage Clients',
    'dashboard.view_messages': 'View Messages',
    'dashboard.file_manager': 'File Manager',
    'dashboard.payments': 'Payments',
    'dashboard.activity.payment_received': 'New payment received from Alice Johnson',
    'dashboard.activity.message_sent': 'Bob Smith sent a new message',
    'dashboard.activity.file_uploaded': 'Carol Davis uploaded a new file',
    'dashboard.activity.client_registered': 'New client registered: David Wilson',
    'dashboard.activity.time_2min': '2 minutes ago',
    'dashboard.activity.time_5min': '5 minutes ago',
    'dashboard.activity.time_10min': '10 minutes ago',
    'dashboard.activity.time_15min': '15 minutes ago',
    // Client dashboard translations
    'client.dashboard.title': 'Client Panel',
    'client.dashboard.welcome': 'Welcome to your portal',
    'client.dashboard.client': 'Client',
    'client.dashboard.subtitle': 'Here is a summary of your account and recent activity.',
    'client.dashboard.last_update': 'Last update',
    'client.dashboard.just_now': 'Just now',
    'client.dashboard.minutes_ago': 'm ago',
    'client.dashboard.hours_ago': 'h ago',
    'client.dashboard.balance': 'Current Balance',
    'client.dashboard.recent_transactions': 'Recent Transactions',
    'client.dashboard.documents': 'Documents',
    'client.dashboard.messages': 'Messages',
    'client.dashboard.payments': 'Payments',
    'client.dashboard.schedule': 'Schedule',
    'client.dashboard.help': 'Help',
    'client.dashboard.settings': 'Settings',
    'client.dashboard.logout': 'Sign Out',
    // Admin clients translations
    'admin.clients.title': 'All Clients',
    'admin.clients.description': 'A list of all your clients and their information',
    'admin.clients.add_client': 'Add Client',
    'admin.clients.total_clients': 'Total Clients',
    'admin.clients.active_clients': 'Active Clients',
    'admin.clients.total_balance': 'Total Balance',
    'admin.clients.search_placeholder': 'Search clients...',
    'admin.clients.name': 'Name',
    'admin.clients.email': 'Email',
    'admin.clients.phone': 'Phone',
    'admin.clients.balance': 'Balance',
    'admin.clients.status': 'Status',
    'admin.clients.last_login': 'Last Login',
    'admin.clients.actions': 'Actions',
    'admin.clients.active': 'Active',
    'admin.clients.inactive': 'Inactive',
    'admin.clients.filter': 'Filter',
    'admin.clients.export': 'Export',
    'admin.clients.client': 'Client',
    'admin.clients.contact': 'Contact',
    // Payments translations (admin page)
    'payments.admin_title': 'Payments',
    'payments.admin_description': 'Manage your payments and account',
    'payments.balance': 'Balance',
    'payments.recharge': 'Recharge',
    'payments.recharge_account': 'Recharge account',
    'payments.presentation': 'Presentation',
    'payments.account_presentation': 'Account presentation',
    'payments.invitation': 'Invitation',
    'payments.invite_friends': 'Invite friends',
    'payments.personal': 'Personal',
    'payments.personal_settings': 'Personal settings',
    'payments.my_bank_card': 'My Bank Card',
    'payments.manage_bank_card': 'Manage bank card',
    'payments.recharge_record': 'Recharge Record',
    'payments.recharge_history': 'Recharge history',
    'payments.withdrawal_records': 'Withdrawal Records',
    'payments.withdrawal_history': 'Withdrawal history',
    'payments.balance_change_record': 'Balance Change Record',
    'payments.balance_change_history': 'Balance change history',
    // Admin settings translations
    'admin.settings.title': 'Admin Settings',
    'admin.settings.description': 'Manage system configuration, user roles, and provider settings',
    'admin.settings.user_management': 'User Management',
    'admin.settings.provider_configurations': 'Provider Configurations',
    'admin.settings.system_settings': 'System Settings',
    'admin.settings.personal_settings': 'Personal Settings',
    'admin.settings.user_role_management': 'User Role Management',
    'admin.settings.user_role_management_desc': 'Manage user roles and permissions. Changes take effect immediately.',
    'admin.settings.no_permission': 'You don\'t have permission to manage users.',
    'admin.settings.you': 'You',
    'admin.settings.offline': 'Offline',
    'admin.settings.last_active': 'Last active',
    'admin.settings.current_role': 'Current Role',
    'admin.settings.cancel': 'Cancel',
    'admin.settings.edit_role': 'Edit Role',
    'admin.settings.role_permissions': 'Role Permissions',
    'admin.settings.role_admin': 'Admin',
    'admin.settings.role_agent': 'Agent',
    'admin.settings.role_viewer': 'Viewer',
    'admin.settings.role_admin_desc': 'Full system access, can manage users and settings',
    'admin.settings.role_agent_desc': 'Can chat with clients, view data, and upload files',
    'admin.settings.role_viewer_desc': 'Read-only access to basic client information',
    'admin.settings.role_no_permissions': 'No permissions',
    'admin.settings.role_admin_1': 'Edit client balances',
    'admin.settings.role_admin_2': 'Manage users',
    'admin.settings.role_admin_3': 'Configure providers',
    'admin.settings.role_admin_4': 'System settings',
    'admin.settings.role_agent_1': 'Chat with clients',
    'admin.settings.role_agent_2': 'View all data',
    'admin.settings.role_agent_3': 'Upload files',
    'admin.settings.role_agent_4': 'View reports',
    'admin.settings.role_viewer_1': 'View basic data',
    'admin.settings.role_viewer_2': 'View reports',
    'admin.settings.role_viewer_3': 'Read-only access',
    // Client documents translations
    'client.documents.title': 'Documents',
    'client.documents.description': 'Access and manage your account documents and reports.',
    'client.documents.search_placeholder': 'Search documents...',
    'client.documents.filter.all': 'All',
    'client.documents.filter.new': 'New',
    'client.documents.filter.viewed': 'Viewed',
    'client.documents.filter.pending': 'Pending',
    'client.documents.status.new': 'New',
    'client.documents.status.viewed': 'Viewed',
    'client.documents.status.signed': 'Signed',
    'client.documents.status.pending': 'Pending',
    'client.documents.status.unknown': 'Unknown',
    'client.documents.actions.view': 'View',
    'client.documents.actions.download': 'Download',
    'client.documents.empty.title': 'No documents found',
    'client.documents.empty.search': 'Try adjusting your search terms.',
    'client.documents.empty.filter': 'No documents match the selected filter.',
    'client.documents.request.title': 'Need a specific document?',
    'client.documents.request.description': 'Can\'t find what you\'re looking for? Contact us and we\'ll help you locate it.',
    'client.documents.request.button': 'Request Document',
    // Client messages translations
    'client.messages.title': 'Messages',
    'client.messages.description': 'Communicate with your financial team and get support.',
    'client.messages.conversations': 'Conversations',
    'client.messages.new_chat': 'New Chat',
    'client.messages.search_placeholder': 'Search conversations...',
    'client.messages.schedule': 'Schedule',
    'client.messages.input_placeholder': 'Type your message...',
    'client.messages.select_conversation': 'Select a conversation',
    'client.messages.select_conversation_desc': 'Choose a conversation from the list to start messaging.',
    // Client payments translations
    'client.payments.title': 'Payments',
    'client.payments.description': 'Manage your payments and view transaction history.',
    'client.payments.total_paid': 'Total Paid',
    'client.payments.all_time': 'All time',
    'client.payments.pending': 'Pending',
    'client.payments.transactions': 'Transactions',
    'client.payments.this_month': 'This Month',
    'client.payments.december_2024': 'December 2024',
    'client.payments.search_placeholder': 'Search payments...',
    'client.payments.filter.all': 'All',
    'client.payments.filter.completed': 'Completed',
    'client.payments.filter.pending': 'Pending',
    'client.payments.filter.failed': 'Failed',
    'client.payments.status.completed': 'Completed',
    'client.payments.status.pending': 'Pending',
    'client.payments.status.failed': 'Failed',
    'client.payments.status.unknown': 'Unknown',
    'client.payments.make_payment': 'Make a Payment',
    'client.payments.make_payment_desc': 'Process new payments or manage your payment methods.',
    'client.payments.new_payment': 'New Payment',
    'client.payments.add_funds': 'Add Funds',
    'client.payments.payment_history': 'Payment History',
    'client.payments.payment_history_desc': 'Your recent payment transactions and status',
    'client.payments.empty.title': 'No payments found',
    'client.payments.empty.search': 'Try adjusting your search terms.',
    'client.payments.empty.filter': 'No payments match the selected filter.',
    // Client settings translations
    'client.settings.title': 'Settings',
    'client.settings.description': 'Manage your account settings and preferences.',
    'client.settings.profile.title': 'Profile Information',
    'client.settings.profile.description': 'Update your personal information and contact details',
    'client.settings.profile.first_name': 'First Name',
    'client.settings.profile.last_name': 'Last Name',
    'client.settings.profile.email': 'Email Address',
    'client.settings.profile.phone': 'Phone Number',
    'client.settings.profile.address': 'Address',
    'client.settings.profile.bio': 'Bio',
    'client.settings.profile.edit_profile': 'Edit Profile',
    'client.settings.profile.save_changes': 'Save Changes',
    'client.settings.profile.cancel': 'Cancel',
    'client.settings.notifications.title': 'Notification Preferences',
    'client.settings.notifications.description': 'Choose how you want to be notified about account activity',
    'client.settings.notifications.email': 'Email Notifications',
    'client.settings.notifications.email_desc': 'Receive notifications via email',
    'client.settings.notifications.sms': 'SMS Notifications',
    'client.settings.notifications.sms_desc': 'Receive notifications via text message',
    'client.settings.notifications.push': 'Push Notifications',
    'client.settings.notifications.push_desc': 'Receive push notifications in browser',
    'client.settings.notifications.marketing': 'Marketing Communications',
    'client.settings.notifications.marketing_desc': 'Receive promotional emails and updates',
    'client.settings.notifications.account_updates': 'Account Updates',
    'client.settings.notifications.account_updates_desc': 'Get notified about account changes',
    'client.settings.notifications.payment_reminders': 'Payment Reminders',
    'client.settings.notifications.payment_reminders_desc': 'Reminders for upcoming payments',
    'client.settings.notifications.meeting_reminders': 'Meeting Reminders',
    'client.settings.notifications.meeting_reminders_desc': 'Reminders for scheduled meetings',
    'client.settings.notifications.save': 'Save Notification Settings',
    'client.settings.security.title': 'Security Settings',
    'client.settings.security.description': 'Manage your account security and privacy settings',
    'client.settings.security.two_factor': 'Two-Factor Authentication',
    'client.settings.security.two_factor_desc': 'Add an extra layer of security to your account',
    'client.settings.security.login_alerts': 'Login Alerts',
    'client.settings.security.login_alerts_desc': 'Get notified when someone logs into your account',
    'client.settings.security.session_timeout': 'Session Timeout (minutes)',
    'client.settings.security.current_password': 'Current Password',
    'client.settings.security.current_password_placeholder': 'Enter current password',
    'client.settings.security.new_password': 'New Password',
    'client.settings.security.new_password_placeholder': 'Enter new password',
    'client.settings.security.confirm_password': 'Confirm New Password',
    'client.settings.security.confirm_password_placeholder': 'Confirm new password',
    'client.settings.security.save': 'Save Security Settings',
    'client.settings.contact.title': 'Contact Information',
    'client.settings.contact.description': 'How to reach your financial team',
    'client.settings.contact.email_support': 'Email Support',
    'client.settings.contact.phone_support': 'Phone Support',
    'client.settings.contact.office_address': 'Office Address',
    'client.settings.contact.business_hours': 'Business Hours',
    'client.settings.contact.emergency_contact': 'Emergency Contact',
    'client.settings.contact.emergency_line': '24/7 Emergency Line',

    // Client Help
    'client.help.title': 'Help & Support',
    'client.help.description': 'Get help and support for your account and services.',
    'client.help.search_placeholder': 'Search help articles...',
    'client.help.contact_support': 'Contact Support',
    'client.help.contact_support_desc': 'Send us a message and we&apos;ll get back to you',
    'client.help.call_us': 'Call Us',
    'client.help.call_us_desc': 'Speak directly with our support team',
    'client.help.video_call': 'Video Call',
    'client.help.video_call_desc': 'Schedule a video call with our team',
    'client.help.help_topics': 'Help Topics',
    'client.help.faq_title': 'Frequently Asked Questions',
    'client.help.no_results': 'No results found',
    'client.help.no_results_desc': 'Try adjusting your search terms',
    'client.help.contact_form_desc': 'Send us a message and we&apos;ll get back to you within 24 hours.',
    'client.help.subject': 'Subject',
    'client.help.subject_placeholder': 'Brief description of your issue',
    'client.help.priority': 'Priority',
    'client.help.priority_low': 'Low',
    'client.help.priority_medium': 'Medium',
    'client.help.priority_high': 'High',
    'client.help.priority_urgent': 'Urgent',
    'client.help.message': 'Message',
    'client.help.message_placeholder': 'Describe your issue in detail...',
    'client.help.send_message': 'Send Message',
    'client.help.cancel': 'Cancel',
    'client.help.additional_resources': 'Additional Resources',
    'client.help.documentation': 'Documentation',
    'client.help.user_guide': 'User Guide',
    'client.help.api_docs': 'API Documentation',
    'client.help.security_best_practices': 'Security Best Practices',
    'client.help.community': 'Community',
    'client.help.community_forum': 'Community Forum',
    'client.help.video_tutorials': 'Video Tutorials',
    'client.help.status_page': 'Status Page',

    // Client Schedule
    'client.schedule.title': 'Schedule',
    'client.schedule.description': 'Manage your meetings and appointments with your financial team.',
    'client.schedule.schedule_meeting': 'Schedule Meeting',
    'client.schedule.upcoming': 'Upcoming',
    'client.schedule.this_month': 'This Month',
    'client.schedule.completed': 'Completed',
    'client.schedule.meetings_scheduled': 'Meetings scheduled',
    'client.schedule.december_2024': 'December 2024',
    'client.schedule.total_meetings': 'Total meetings',
    'client.schedule.new_meeting': 'Schedule New Meeting',
    'client.schedule.create_meeting': 'Create a new meeting with your financial advisor',
    'client.schedule.meeting_title': 'Meeting Title',
    'client.schedule.date': 'Date',
    'client.schedule.time': 'Time',
    'client.schedule.meeting_type': 'Meeting Type',
    'client.schedule.video_call': 'Video Call',
    'client.schedule.in_person': 'In-Person',
    'client.schedule.phone_call': 'Phone Call',
    'client.schedule.notes_optional': 'Notes (Optional)',
    'client.schedule.any_additional_notes': 'Any additional notes or agenda items...',
    'client.schedule.schedule_meeting_button': 'Schedule Meeting',
    'client.schedule.cancel': 'Cancel',
    'client.schedule.upcoming_meetings': 'Upcoming Meetings',
    'client.schedule.scheduled_meetings': 'Your scheduled meetings and appointments',
    'client.schedule.meeting_history': 'Meeting History',
    'client.schedule.completed_meetings': 'Your completed meetings and appointments',
    'client.schedule.no_upcoming_meetings': 'No upcoming meetings',
    'client.schedule.schedule_meeting_to_start': 'Schedule a meeting to get started.',
    'client.schedule.no_completed_meetings': 'No completed meetings',
    'client.schedule.meeting_history_will_appear': 'Your meeting history will appear here.',
    'client.schedule.cancelled': 'Cancelled',
    'client.schedule.unknown': 'Unknown',

    // Investment analytics translations
    'investments.title': 'Investment Analytics',
    'investments.description': 'Visualize investment performance and portfolio data',
    'investments.total_portfolio_value': 'Total Portfolio Value',
    'investments.this_month_growth': '+12.4% this month',
    'investments.active_investments': 'Active Investments',
    'investments.across_sectors': 'Across 8 sectors',
    'investments.monthly_return': 'Monthly Return',
    'investments.above_benchmark': 'Above benchmark',
    'investments.risk_score': 'Risk Score',
    'investments.moderate_risk': 'Moderate risk',
    'investments.quick_actions': 'Quick Actions',
    'investments.quick_actions_desc': 'Manage your investment data and reports',
    'investments.upload_data': 'Upload Data',
    'investments.export_report': 'Export Report',
    'investments.generate_analysis': 'Generate Analysis',
    'investments.schedule_report': 'Schedule Report',
    'investments.data_visualization': 'Investment Data Visualization',
    'investments.performance': 'Investment Performance',
    'investments.line_chart': 'Line Chart',
    'investments.sample_data': 'Sample Data',
    'investments.upload_data_chart': 'Upload Data',
    'investments.dynamic_chart': 'Dynamic Chart Images Charts',
    'investments.portfolio_allocation': 'Portfolio Allocation',
    'investments.current_asset_distribution': 'Current asset distribution',
    'investments.stocks': 'Stocks',
    'investments.bonds': 'Bonds',
    'investments.cash': 'Cash',
    'investments.recent_performance': 'Recent Performance',
    'investments.last_30_days_performance': 'Last 30 days performance',
    'investments.portfolio': 'Portfolio',
    'investments.image_gallery': 'Image Gallery',
    'investments.images': 'Images',
    'investments.charts': 'Charts',
    // Client schedule translations
    'schedule.title': 'Schedule',
    'schedule.description': 'Manage your meetings and appointments with your financial team.',
    'schedule.schedule_meeting': 'Schedule Meeting',
    'schedule.upcoming': 'Upcoming',
    'schedule.this_month': 'This Month',
    'schedule.completed': 'Completed',
    'schedule.meetings_scheduled': 'Meetings scheduled',
    'schedule.december_2024': 'December 2024',
    'schedule.total_meetings': 'Total meetings',
    'schedule.new_meeting': 'Schedule New Meeting',
    'schedule.create_meeting': 'Create a new meeting with your financial advisor',
    'schedule.meeting_title': 'Meeting Title',
    'schedule.date': 'Date',
    'schedule.time': 'Time',
    'schedule.meeting_type': 'Meeting Type',
    'schedule.video_call': 'Video Call',
    'schedule.in_person': 'In-Person',
    'schedule.phone_call': 'Phone Call',
    'schedule.notes_optional': 'Notes (Optional)',
    'schedule.any_additional_notes': 'Any additional notes or agenda items...',
    'schedule.cancel': 'Cancel',
    'schedule.upcoming_meetings': 'Upcoming Meetings',
    'schedule.scheduled_meetings': 'Your scheduled meetings and appointments',
    'schedule.meeting_history': 'Meeting History',
    'schedule.completed_meetings': 'Your completed meetings and appointments',
    'schedule.no_upcoming_meetings': 'No upcoming meetings',
    'schedule.schedule_meeting_to_start': 'Schedule a meeting to get started.',
    'schedule.no_completed_meetings': 'No completed meetings',
    'schedule.meeting_history_will_appear': 'Your meeting history will appear here.',
    'client.dashboard.refresh': 'Refresh',
    'client.dashboard.export': 'Export',
    'client.dashboard.withdraw': 'Withdraw',
    'client.dashboard.new_payment': 'New Payment',
    'client.dashboard.available_balance': 'Available Balance',
    'client.dashboard.total_invested': 'Total Invested',
    'client.dashboard.monthly_return': 'Monthly Return',
    'client.dashboard.active_investments': 'Active Investments',
    'client.dashboard.notifications': 'Notifications',
    'client.dashboard.new_alerts': 'New alerts',
    'client.dashboard.new_this_week': 'new this week',
    'client.dashboard.unread': 'unread',
    'client.dashboard.from_last_month': 'from last month',
    'client.dashboard.investment_analytics': 'Investment Analytics',
    'client.dashboard.visualize_portfolio': 'Visualize your portfolio performance and asset allocation',
    'client.dashboard.portfolio_performance': 'Portfolio Performance',
    'client.dashboard.asset_allocation': 'Asset Allocation',
    'client.dashboard.monthly_returns': 'Monthly Returns',
    'client.dashboard.interactive_chart': 'Interactive chart visualization',
    'client.dashboard.portfolio_value': 'Portfolio Value',
    'client.dashboard.best_month': 'Best Month',
    'client.dashboard.worst_month': 'Worst Month',
    'client.dashboard.current_value': 'Current Value',
    'client.dashboard.return': 'return',
    // Demo login translations
    'demo.mode.title': 'Demo Mode',
    'demo.mode.description': 'Click the buttons below to test different user types:',
    'demo.admin.title': 'Admin Dashboard',
    'demo.admin.description': 'Access the admin panel with full management capabilities:',
    'demo.admin.feature1': 'Manage all clients and their accounts',
    'demo.admin.feature2': 'View system analytics and reports',
    'demo.admin.feature3': 'Access payment processing controls',
    'demo.admin.feature4': 'Monitor user activity and messages',
    'demo.admin.feature5': 'System configuration and settings',
    'demo.admin.button': 'Login as Admin',
    'demo.admin.user_name': 'Admin User',
    'demo.client.title': 'Client Portal',
    'demo.client.description': 'Experience the client dashboard with personal features:',
    'demo.client.feature1': 'View account balance and transactions',
    'demo.client.feature2': 'Make payments and withdrawals',
    'demo.client.feature3': 'Access investment reports and charts',
    'demo.client.feature4': 'Communicate with support team',
    'demo.client.feature5': 'Manage personal documents and files',
    'demo.client.button': 'Login as Client',
    'demo.client.user_name': 'Client User',
    'demo.note.title': 'Note:',
    'demo.note.description': 'Both demo accounts use mock data. In a real application, these would be actual user accounts with real data and permissions.',
    'demo.email.title': 'Email Authentication',
    'demo.email.description': 'You can also test the authentication flow using these demo email addresses:',
    'demo.email.admin': 'Admin Dashboard',
    'demo.email.client': 'Client Portal',
    'demo.email.instruction': 'Enter either email above and click "Send Magic Link" to test the full authentication flow.',
    // Navigation translations
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    // Client chat translations
    'client.chat.schedule_call': 'Schedule Call',
    'client.chat.schedule_call_desc': 'Book a phone consultation with your advisor',
    'client.chat.video_meeting': 'Video Meeting',
    'client.chat.video_meeting_desc': 'Start a video call with your team',
    'client.chat.send_email': 'Send Email',
    'client.chat.send_email_desc': 'Send a detailed message via email',
    'client.chat.need_assistance': 'Need Immediate Assistance?',
    'client.chat.support_available': 'Our support team is available 24/7 for urgent matters.',
    'client.chat.call_now': 'Call Now',
    'client.chat.email': 'Email',
    // Client payments translations
    'client.payments.need_help': 'Need Help with Payments?',
    'client.payments.contact_support_desc': 'Contact our support team for assistance with payment processing.',
    'client.payments.contact_support': 'Contact Support',
    // Client footer translations
    'client.footer.description': 'Your secure gateway to manage your account, view documents, and communicate with our team.',
    'client.footer.email': 'Email',
    'client.footer.call': 'Call',
    'client.footer.quick_links': 'Quick Links',
    'client.footer.dashboard': 'Dashboard',
    'client.footer.documents': 'Documents',
    'client.footer.messages': 'Messages',
    'client.footer.billing': 'Billing',
    'client.footer.support': 'Support',
    'client.footer.help_center': 'Help Center',
    'client.footer.live_chat': 'Live Chat',
    'client.footer.contact_support': 'Contact Support',
    'client.footer.faq': 'FAQ',
    'client.footer.contact_us': 'Contact Us',
    'client.footer.live_chat_available': 'Live Chat Available',
    'client.footer.all_rights_reserved': 'Client Portal. All rights reserved.',
    'client.footer.privacy_policy': 'Privacy Policy',
    'client.footer.terms_of_service': 'Terms of Service',
    'client.footer.made_with': 'Made with',
    'client.footer.for_our_clients': 'for our clients',
    // Gallery translations
    'gallery.upload': 'Upload',
    'gallery.uploading': 'Uploading...',
  },
  es: {
    'dashboard.title': 'Panel de Control',
    'dashboard.description': '¡Bienvenido de vuelta! Aquí está lo que está pasando.',
    'payments.title': 'Pagos',
    'payments.description': 'Gestiona pagos y transacciones',
    'clients.title': 'Todos los Clientes',
    'clients.description': 'Una lista de todos tus clientes y su información',
    'settings.title': 'Configuración',
    'settings.description': 'Gestiona la configuración de tu aplicación',
    'theme.light': 'Modo Claro',
    'theme.dark': 'Modo Oscuro',
    'theme.system': 'Sistema',
    'language.english': 'English',
    'language.spanish': 'Español',
    'button.add_client': 'Agregar Cliente',
    'button.process_payment': 'Procesar Pago',
    'button.filter': 'Filtrar',
    'button.export': 'Exportar',
    'button.save': 'Guardar',
    'button.cancel': 'Cancelar',
    'button.edit': 'Editar',
    'button.delete': 'Eliminar',
    'button.view': 'Ver',
    'status.active': 'Activo',
    'status.inactive': 'Inactivo',
    'status.pending': 'Pendiente',
    'status.completed': 'Completado',
    // Common translations
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.close': 'Cerrar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.submit': 'Enviar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.sign_in': 'Iniciar Sesión',
    'common.get_started': 'Comenzar',
    // Home page translations
    'home.stats.active_users': 'Usuarios Activos',
    'home.stats.messages_sent': 'Mensajes Enviados',
    'home.stats.payments_processed': 'Pagos Procesados',
    'home.stats.customer_satisfaction': 'Satisfacción del Cliente',
    'home.hero.title': 'Plataforma de Comunicación con Clientes',
    'home.hero.description': 'Optimiza tus relaciones con clientes con nuestra plataforma integral de comunicación y gestión.',
    'home.hero.get_started': 'Comenzar Prueba Gratuita',
    'home.features.title': 'Todo lo que necesitas para gestionar clientes',
    'home.features.subtitle': 'Nuestra plataforma proporciona todas las herramientas que necesitas para construir y mantener relaciones sólidas con los clientes.',
    'home.features.clients.title': 'Gestión de Clientes',
    'home.features.clients.description': 'Base de datos completa de clientes con perfiles detallados, historial de interacciones y seguimiento de relaciones.',
    'home.features.communication.title': 'Centro de Comunicación',
    'home.features.communication.description': 'Sistema de mensajería unificado con email, SMS y notificaciones en la aplicación para una comunicación fluida con los clientes.',
    'home.features.payments.title': 'Procesamiento de Pagos',
    'home.features.payments.description': 'Procesamiento seguro de pagos con múltiples métodos de pago y facturación automatizada.',
    'home.features.analytics.title': 'Análisis de Inversiones',
    'home.features.analytics.description': 'Herramientas avanzadas de análisis e informes para rastrear el rendimiento y tomar decisiones basadas en datos.',
    'home.features.security.title': 'Seguridad y Privacidad',
    'home.features.security.description': 'Seguridad de nivel empresarial con control de acceso basado en roles y cifrado de datos.',
    'home.features.dashboard.title': 'Panel de Análisis',
    'home.features.dashboard.description': 'Insights en tiempo real y métricas de rendimiento para ayudarte a tomar decisiones informadas.',
    'home.demo.title': 'Instrucciones de Demo',
    'home.demo.subtitle': 'Este es un proyecto de demostración que muestra las capacidades de la plataforma. Usa los botones de abajo para probar diferentes experiencias de usuario.',
    'home.demo.admin.title': 'Panel de Administración',
    'home.demo.admin.description': 'Experimenta la interfaz completa de administración con gestión de clientes, análisis y controles del sistema.',
    'home.demo.admin.button': 'Iniciar como Admin',
    'home.demo.client.title': 'Portal del Cliente',
    'home.demo.client.description': 'Ve la interfaz orientada al cliente con gestión de cuentas, pagos y características de comunicación.',
    'home.demo.client.button': 'Iniciar como Cliente',
    'home.demo.note': 'Para el flujo completo de autenticación, usa las direcciones de email de abajo con autenticación de enlace mágico.',
    'home.footer.company': 'Empresa',
    'home.footer.product': 'Producto',
    'home.footer.resources': 'Recursos',
    'home.footer.legal': 'Legal',
    'home.footer.about': 'Acerca de Nosotros',
    'home.footer.careers': 'Carreras',
    'home.footer.contact': 'Contacto',
    'home.footer.features': 'Características',
    'home.footer.pricing': 'Precios',
    'home.footer.documentation': 'Documentación',
    'home.footer.support': 'Soporte',
    'home.footer.privacy': 'Política de Privacidad',
    'home.footer.terms': 'Términos de Servicio',
    'home.footer.cookies': 'Política de Cookies',
    'home.footer.rights': 'Todos los derechos reservados.',
    // Login page translations
    'login.title': 'Iniciar Sesión',
    'login.subtitle': '¡Bienvenido de vuelta! Por favor inicia sesión en tu cuenta.',
    'login.email.label': 'Dirección de Email',
    'login.email.placeholder': 'Ingresa tu email',
    'login.password.label': 'Contraseña',
    'login.password.placeholder': 'Ingresa tu contraseña',
    'login.remember': 'Recordarme',
    'login.forgot': '¿Olvidaste tu contraseña?',
    'login.signin': 'Iniciar Sesión',
    'login.or': 'O continúa con',
    'login.google': 'Continuar con Google',
    'login.magic_link': 'Enviar Enlace Mágico',
    'login.whatsapp': 'WhatsApp',
    'login.no_account': '¿No tienes una cuenta?',
    'login.signup': 'Regístrate',
    'login.demo.title': 'Modo Demo',
    'login.demo.description': 'Haz clic en los botones de abajo para probar diferentes tipos de usuario:',
    'login.auth_info.title': 'Autenticación por Email',
    'login.auth_info.description': 'También puedes probar el flujo de autenticación usando estas direcciones de email demo:',
    'login.auth_info.admin': 'Panel de Administración',
    'login.auth_info.client': 'Portal del Cliente',
    'login.auth_info.instruction': 'Ingresa cualquiera de los emails de arriba y haz clic en "Enviar Enlace Mágico" para probar el flujo completo de autenticación.',
    'login.method.email': 'Email',
    'login.method.whatsapp': 'WhatsApp',
    'login.whatsapp.title': 'Inicio de Sesión con WhatsApp',
    'login.whatsapp.description': 'Ingresa tu número de teléfono para recibir un código de verificación por WhatsApp',
    'login.whatsapp.phone_label': 'Número de Teléfono',
    'login.whatsapp.phone_placeholder': '(123) 456-7890',
    'login.whatsapp.code_description': 'Enviaremos un código de 6 dígitos a este número por WhatsApp',
    'login.whatsapp.send_code': 'Enviar Código de WhatsApp',
    'login.whatsapp.verify_code': 'Código de Verificación',
    'login.whatsapp.code_placeholder': '123456',
    'login.whatsapp.success_message': '¡Código de verificación de WhatsApp enviado!',
    'login.whatsapp.error_invalid_phone': 'Por favor ingresa un número de teléfono válido',
    'login.whatsapp.error_invalid_code': 'Por favor ingresa el código de verificación de 6 dígitos',
    'login.whatsapp.disclaimer': 'Al continuar, aceptas recibir mensajes por WhatsApp',
    'login.whatsapp.resend_code': 'Reenviar Código',
    'login.whatsapp.back_to_phone': 'Volver al Número de Teléfono',
    // Dashboard translations
    'dashboard.welcome': 'Bienvenido de vuelta',
    'dashboard.overview': 'Aquí tienes un resumen de tu cuenta y actividad reciente.',
    'dashboard.recent_activity': 'Actividad Reciente',
    'dashboard.quick_actions': 'Acciones Rápidas',
    'dashboard.total_clients': 'Total de Clientes',
    'dashboard.active_payments': 'Pagos Activos',
    'dashboard.total_revenue': 'Ingresos Totales',
    'dashboard.pending_tasks': 'Tareas Pendientes',
    'dashboard.view_all': 'Ver Todo',
    'dashboard.add_client': 'Agregar Cliente',
    'dashboard.process_payment': 'Procesar Pago',
    'dashboard.send_message': 'Enviar Mensaje',
    'dashboard.create_report': 'Crear Reporte',
    'dashboard.active_conversations': 'Conversaciones Activas',
    'dashboard.files_uploaded': 'Archivos Subidos',
    'dashboard.recent_activity_desc': 'Últimas actualizaciones de tus clientes',
    'dashboard.quick_actions_desc': 'Tareas comunes y accesos directos',
    'dashboard.manage_clients': 'Gestionar Clientes',
    'dashboard.view_messages': 'Ver Mensajes',
    'dashboard.file_manager': 'Gestor de Archivos',
    'dashboard.payments': 'Pagos',
    'dashboard.activity.payment_received': 'Nuevo pago recibido de Alice Johnson',
    'dashboard.activity.message_sent': 'Bob Smith envió un nuevo mensaje',
    'dashboard.activity.file_uploaded': 'Carol Davis subió un nuevo archivo',
    'dashboard.activity.client_registered': 'Nuevo cliente registrado: David Wilson',
    'dashboard.activity.time_2min': 'hace 2 minutos',
    'dashboard.activity.time_5min': 'hace 5 minutos',
    'dashboard.activity.time_10min': 'hace 10 minutos',
    'dashboard.activity.time_15min': 'hace 15 minutos',
    // Client dashboard translations
    'client.dashboard.title': 'Panel del Cliente',
    'client.dashboard.welcome': 'Bienvenido a tu portal',
    'client.dashboard.client': 'Cliente',
    'client.dashboard.subtitle': 'Aquí tienes un resumen de tu cuenta y actividad reciente.',
    'client.dashboard.last_update': 'Última actualización',
    'client.dashboard.just_now': 'Ahora mismo',
    'client.dashboard.minutes_ago': 'm atrás',
    'client.dashboard.hours_ago': 'h atrás',
    'client.dashboard.balance': 'Saldo Actual',
    'client.dashboard.recent_transactions': 'Transacciones Recientes',
    'client.dashboard.documents': 'Documentos',
    'client.dashboard.messages': 'Mensajes',
    'client.dashboard.payments': 'Pagos',
    'client.dashboard.schedule': 'Programar',
    'client.dashboard.help': 'Ayuda',
    'client.dashboard.settings': 'Configuración',
    'client.dashboard.logout': 'Cerrar Sesión',
    // Admin clients translations
    'admin.clients.title': 'Todos los Clientes',
    'admin.clients.description': 'Una lista de todos tus clientes y su información',
    'admin.clients.add_client': 'Agregar Cliente',
    'admin.clients.total_clients': 'Total de Clientes',
    'admin.clients.active_clients': 'Clientes Activos',
    'admin.clients.total_balance': 'Balance Total',
    'admin.clients.search_placeholder': 'Buscar clientes...',
    'admin.clients.name': 'Nombre',
    'admin.clients.email': 'Correo',
    'admin.clients.phone': 'Teléfono',
    'admin.clients.balance': 'Balance',
    'admin.clients.status': 'Estado',
    'admin.clients.last_login': 'Último Acceso',
    'admin.clients.actions': 'Acciones',
    'admin.clients.active': 'Activo',
    'admin.clients.inactive': 'Inactivo',
    'admin.clients.filter': 'Filtrar',
    'admin.clients.export': 'Exportar',
    'admin.clients.client': 'Cliente',
    'admin.clients.contact': 'Contacto',
    // Payments translations (admin page)
    'payments.admin_title': 'Pagos',
    'payments.admin_description': 'Gestiona tus pagos y cuenta',
    'payments.balance': 'Balance',
    'payments.recharge': 'Recargar',
    'payments.recharge_account': 'Recargar cuenta',
    'payments.presentation': 'Presentación',
    'payments.account_presentation': 'Presentación de cuenta',
    'payments.invitation': 'Invitación',
    'payments.invite_friends': 'Invitar amigos',
    'payments.personal': 'Personal',
    'payments.personal_settings': 'Configuración personal',
    'payments.my_bank_card': 'Mi Tarjeta Bancaria',
    'payments.manage_bank_card': 'Gestionar tarjeta bancaria',
    'payments.recharge_record': 'Registro de Recarga',
    'payments.recharge_history': 'Historial de recargas',
    'payments.withdrawal_records': 'Registros de Retiro',
    'payments.withdrawal_history': 'Historial de retiros',
    'payments.balance_change_record': 'Registro de Cambio de Balance',
    'payments.balance_change_history': 'Historial de cambios de balance',
    // Admin settings translations
    'admin.settings.title': 'Configuración de Administrador',
    'admin.settings.description': 'Gestiona la configuración del sistema, roles de usuario y configuraciones de proveedores',
    'admin.settings.user_management': 'Gestión de Usuarios',
    'admin.settings.provider_configurations': 'Configuraciones de Proveedores',
    'admin.settings.system_settings': 'Configuraciones del Sistema',
    'admin.settings.personal_settings': 'Configuraciones Personales',
    'admin.settings.user_role_management': 'Gestión de Roles de Usuario',
    'admin.settings.user_role_management_desc': 'Gestiona roles de usuario y permisos. Los cambios toman efecto inmediatamente.',
    'admin.settings.no_permission': 'No tienes permisos para gestionar usuarios.',
    'admin.settings.you': 'Tú',
    'admin.settings.offline': 'Desconectado',
    'admin.settings.last_active': 'Última actividad',
    'admin.settings.current_role': 'Rol Actual',
    'admin.settings.cancel': 'Cancelar',
    'admin.settings.edit_role': 'Editar Rol',
    'admin.settings.role_permissions': 'Permisos de Rol',
    'admin.settings.role_admin': 'Administrador',
    'admin.settings.role_agent': 'Agente',
    'admin.settings.role_viewer': 'Visualizador',
    'admin.settings.role_admin_desc': 'Acceso completo al sistema, puede gestionar usuarios y configuraciones',
    'admin.settings.role_agent_desc': 'Puede chatear con clientes, ver datos y subir archivos',
    'admin.settings.role_viewer_desc': 'Acceso de solo lectura a información básica del cliente',
    'admin.settings.role_no_permissions': 'Sin permisos',
    'admin.settings.role_admin_1': 'Editar balances de clientes',
    'admin.settings.role_admin_2': 'Gestionar usuarios',
    'admin.settings.role_admin_3': 'Configurar proveedores',
    'admin.settings.role_admin_4': 'Configuraciones del sistema',
    'admin.settings.role_agent_1': 'Chatear con clientes',
    'admin.settings.role_agent_2': 'Ver todos los datos',
    'admin.settings.role_agent_3': 'Subir archivos',
    'admin.settings.role_agent_4': 'Ver reportes',
    'admin.settings.role_viewer_1': 'Ver datos básicos',
    'admin.settings.role_viewer_2': 'Ver reportes',
    'admin.settings.role_viewer_3': 'Acceso de solo lectura',
    // Client documents translations
    'client.documents.title': 'Documentos',
    'client.documents.description': 'Accede y gestiona los documentos e informes de tu cuenta.',
    'client.documents.search_placeholder': 'Buscar documentos...',
    'client.documents.filter.all': 'Todos',
    'client.documents.filter.new': 'Nuevos',
    'client.documents.filter.viewed': 'Vistos',
    'client.documents.filter.pending': 'Pendientes',
    'client.documents.status.new': 'Nuevo',
    'client.documents.status.viewed': 'Visto',
    'client.documents.status.signed': 'Firmado',
    'client.documents.status.pending': 'Pendiente',
    'client.documents.status.unknown': 'Desconocido',
    'client.documents.actions.view': 'Ver',
    'client.documents.actions.download': 'Descargar',
    'client.documents.empty.title': 'No se encontraron documentos',
    'client.documents.empty.search': 'Intenta ajustar tus términos de búsqueda.',
    'client.documents.empty.filter': 'Ningún documento coincide con el filtro seleccionado.',
    'client.documents.request.title': '¿Necesitas un documento específico?',
    'client.documents.request.description': '¿No encuentras lo que buscas? Contáctanos y te ayudaremos a localizarlo.',
    'client.documents.request.button': 'Solicitar Documento',
    // Client messages translations
    'client.messages.title': 'Mensajes',
    'client.messages.description': 'Comunícate con tu equipo financiero y obtén soporte.',
    'client.messages.conversations': 'Conversaciones',
    'client.messages.new_chat': 'Nuevo Chat',
    'client.messages.search_placeholder': 'Buscar conversaciones...',
    'client.messages.schedule': 'Programar',
    'client.messages.input_placeholder': 'Escribe tu mensaje...',
    'client.messages.select_conversation': 'Selecciona una conversación',
    'client.messages.select_conversation_desc': 'Elige una conversación de la lista para comenzar a chatear.',
    // Client payments translations
    'client.payments.title': 'Pagos',
    'client.payments.description': 'Gestiona tus pagos y ve el historial de transacciones.',
    'client.payments.total_paid': 'Total Pagado',
    'client.payments.all_time': 'Todo el tiempo',
    'client.payments.pending': 'Pendiente',
    'client.payments.transactions': 'Transacciones',
    'client.payments.this_month': 'Este Mes',
    'client.payments.december_2024': 'Diciembre 2024',
    'client.payments.search_placeholder': 'Buscar pagos...',
    'client.payments.filter.all': 'Todos',
    'client.payments.filter.completed': 'Completados',
    'client.payments.filter.pending': 'Pendientes',
    'client.payments.filter.failed': 'Fallidos',
    'client.payments.status.completed': 'Completado',
    'client.payments.status.pending': 'Pendiente',
    'client.payments.status.failed': 'Fallido',
    'client.payments.status.unknown': 'Desconocido',
    'client.payments.make_payment': 'Hacer un Pago',
    'client.payments.make_payment_desc': 'Procesa nuevos pagos o gestiona tus métodos de pago.',
    'client.payments.new_payment': 'Nuevo Pago',
    'client.payments.add_funds': 'Agregar Fondos',
    'client.payments.payment_history': 'Historial de Pagos',
    'client.payments.payment_history_desc': 'Tus transacciones de pago recientes y estado',
    'client.payments.empty.title': 'No se encontraron pagos',
    'client.payments.empty.search': 'Intenta ajustar tus términos de búsqueda.',
    'client.payments.empty.filter': 'Ningún pago coincide con el filtro seleccionado.',
    // Client settings translations
    'client.settings.title': 'Configuración',
    'client.settings.description': 'Gestiona la configuración de tu cuenta y preferencias.',
    'client.settings.profile.title': 'Información del Perfil',
    'client.settings.profile.description': 'Actualiza tu información personal y datos de contacto',
    'client.settings.profile.first_name': 'Nombre',
    'client.settings.profile.last_name': 'Apellido',
    'client.settings.profile.email': 'Correo Electrónico',
    'client.settings.profile.phone': 'Número de Teléfono',
    'client.settings.profile.address': 'Dirección',
    'client.settings.profile.bio': 'Biografía',
    'client.settings.profile.edit_profile': 'Editar Perfil',
    'client.settings.profile.save_changes': 'Guardar Cambios',
    'client.settings.profile.cancel': 'Cancelar',
    'client.settings.notifications.title': 'Preferencias de Notificaciones',
    'client.settings.notifications.description': 'Elige cómo quieres ser notificado sobre la actividad de tu cuenta',
    'client.settings.notifications.email': 'Notificaciones por Email',
    'client.settings.notifications.email_desc': 'Recibe notificaciones por correo electrónico',
    'client.settings.notifications.sms': 'Notificaciones por SMS',
    'client.settings.notifications.sms_desc': 'Recibe notificaciones por mensaje de texto',
    'client.settings.notifications.push': 'Notificaciones Push',
    'client.settings.notifications.push_desc': 'Recibe notificaciones push en el navegador',
    'client.settings.notifications.marketing': 'Comunicaciones de Marketing',
    'client.settings.notifications.marketing_desc': 'Recibe emails promocionales y actualizaciones',
    'client.settings.notifications.account_updates': 'Actualizaciones de Cuenta',
    'client.settings.notifications.account_updates_desc': 'Recibe notificaciones sobre cambios en tu cuenta',
    'client.settings.notifications.payment_reminders': 'Recordatorios de Pago',
    'client.settings.notifications.payment_reminders_desc': 'Recordatorios para pagos próximos',
    'client.settings.notifications.meeting_reminders': 'Recordatorios de Reuniones',
    'client.settings.notifications.meeting_reminders_desc': 'Recordatorios para reuniones programadas',
    'client.settings.notifications.save': 'Guardar Configuración de Notificaciones',
    'client.settings.security.title': 'Configuración de Seguridad',
    'client.settings.security.description': 'Gestiona la seguridad de tu cuenta y configuración de privacidad',
    'client.settings.security.two_factor': 'Autenticación de Dos Factores',
    'client.settings.security.two_factor_desc': 'Añade una capa extra de seguridad a tu cuenta',
    'client.settings.security.login_alerts': 'Alertas de Inicio de Sesión',
    'client.settings.security.login_alerts_desc': 'Recibe notificaciones cuando alguien inicie sesión en tu cuenta',
    'client.settings.security.session_timeout': 'Tiempo de Expiración de Sesión (minutos)',
    'client.settings.security.current_password': 'Contraseña Actual',
    'client.settings.security.current_password_placeholder': 'Ingresa la contraseña actual',
    'client.settings.security.new_password': 'Nueva Contraseña',
    'client.settings.security.new_password_placeholder': 'Ingresa la nueva contraseña',
    'client.settings.security.confirm_password': 'Confirmar Nueva Contraseña',
    'client.settings.security.confirm_password_placeholder': 'Confirma la nueva contraseña',
    'client.settings.security.save': 'Guardar Configuración de Seguridad',
    'client.settings.contact.title': 'Información de Contacto',
    'client.settings.contact.description': 'Cómo contactar a tu equipo financiero',
    'client.settings.contact.email_support': 'Soporte por Email',
    'client.settings.contact.phone_support': 'Soporte por Teléfono',
    'client.settings.contact.office_address': 'Dirección de la Oficina',
    'client.settings.contact.business_hours': 'Horario de Atención',
    'client.settings.contact.emergency_contact': 'Contacto de Emergencia',
    'client.settings.contact.emergency_line': 'Línea de Emergencia 24/7',

    // Client Help
    'client.help.title': 'Ayuda y Soporte',
    'client.help.description': 'Obtén ayuda y soporte para tu cuenta y servicios.',
    'client.help.search_placeholder': 'Buscar artículos de ayuda...',
    'client.help.contact_support': 'Contactar Soporte',
    'client.help.contact_support_desc': 'Envíanos un mensaje y te responderemos',
    'client.help.call_us': 'Llámanos',
    'client.help.call_us_desc': 'Habla directamente con nuestro equipo de soporte',
    'client.help.video_call': 'Videollamada',
    'client.help.video_call_desc': 'Programa una videollamada con nuestro equipo',
    'client.help.help_topics': 'Temas de Ayuda',
    'client.help.faq_title': 'Preguntas Frecuentes',
    'client.help.no_results': 'No se encontraron resultados',
    'client.help.no_results_desc': 'Intenta ajustar tus términos de búsqueda',
    'client.help.contact_form_desc': 'Envíanos un mensaje y te responderemos dentro de 24 horas.',
    'client.help.subject': 'Asunto',
    'client.help.subject_placeholder': 'Breve descripción de tu problema',
    'client.help.priority': 'Prioridad',
    'client.help.priority_low': 'Baja',
    'client.help.priority_medium': 'Media',
    'client.help.priority_high': 'Alta',
    'client.help.priority_urgent': 'Urgente',
    'client.help.message': 'Mensaje',
    'client.help.message_placeholder': 'Describe tu problema en detalle...',
    'client.help.send_message': 'Enviar Mensaje',
    'client.help.cancel': 'Cancelar',
    'client.help.additional_resources': 'Recursos Adicionales',
    'client.help.documentation': 'Documentación',
    'client.help.user_guide': 'Guía de Usuario',
    'client.help.api_docs': 'Documentación de API',
    'client.help.security_best_practices': 'Mejores Prácticas de Seguridad',
    'client.help.community': 'Comunidad',
    'client.help.community_forum': 'Foro de la Comunidad',
    'client.help.video_tutorials': 'Tutoriales en Video',
    'client.help.status_page': 'Página de Estado',

    // Client Schedule
    'client.schedule.title': 'Programar',
    'client.schedule.description': 'Gestiona tus reuniones y citas con tu equipo financiero.',
    'client.schedule.schedule_meeting': 'Programar Reunión',
    'client.schedule.upcoming': 'Próximas',
    'client.schedule.this_month': 'Este Mes',
    'client.schedule.completed': 'Completadas',
    'client.schedule.meetings_scheduled': 'Reuniones programadas',
    'client.schedule.december_2024': 'Diciembre 2024',
    'client.schedule.total_meetings': 'Total de reuniones',
    'client.schedule.new_meeting': 'Programar Nueva Reunión',
    'client.schedule.create_meeting': 'Crear una nueva reunión con tu asesor financiero',
    'client.schedule.meeting_title': 'Título de la Reunión',
    'client.schedule.date': 'Fecha',
    'client.schedule.time': 'Hora',
    'client.schedule.meeting_type': 'Tipo de Reunión',
    'client.schedule.video_call': 'Llamada de Video',
    'client.schedule.in_person': 'En Persona',
    'client.schedule.phone_call': 'Llamada Telefónica',
    'client.schedule.notes_optional': 'Notas (Opcional)',
    'client.schedule.any_additional_notes': 'Cualquier nota adicional o elementos de agenda...',
    'client.schedule.schedule_meeting_button': 'Programar Reunión',
    'client.schedule.cancel': 'Cancelar',
    'client.schedule.upcoming_meetings': 'Reuniones Próximas',
    'client.schedule.scheduled_meetings': 'Tus reuniones y citas programadas',
    'client.schedule.meeting_history': 'Historial de Reuniones',
    'client.schedule.completed_meetings': 'Tus reuniones y citas completadas',
    'client.schedule.no_upcoming_meetings': 'No hay reuniones próximas',
    'client.schedule.schedule_meeting_to_start': 'Programa una reunión para comenzar.',
    'client.schedule.no_completed_meetings': 'No hay reuniones completadas',
    'client.schedule.meeting_history_will_appear': 'Tu historial de reuniones aparecerá aquí.',
    'client.schedule.cancelled': 'Cancelada',
    'client.schedule.unknown': 'Desconocida',

    // Investment analytics translations
    'investments.title': 'Análisis de Inversiones',
    'investments.description': 'Visualiza el rendimiento de inversiones y datos de cartera',
    'investments.total_portfolio_value': 'Valor Total de la Cartera',
    'investments.this_month_growth': '+12.4% este mes',
    'investments.active_investments': 'Inversiones Activas',
    'investments.across_sectors': 'En 8 sectores',
    'investments.monthly_return': 'Retorno Mensual',
    'investments.above_benchmark': 'Por encima del benchmark',
    'investments.risk_score': 'Puntuación de Riesgo',
    'investments.moderate_risk': 'Riesgo moderado',
    'investments.quick_actions': 'Acciones Rápidas',
    'investments.quick_actions_desc': 'Gestiona tus datos de inversión y reportes',
    'investments.upload_data': 'Subir Datos',
    'investments.export_report': 'Exportar Reporte',
    'investments.generate_analysis': 'Generar Análisis',
    'investments.schedule_report': 'Programar Reporte',
    'investments.data_visualization': 'Visualización de Datos de Inversión',
    'investments.performance': 'Rendimiento de Inversión',
    'investments.line_chart': 'Gráfico de Líneas',
    'investments.sample_data': 'Datos de Muestra',
    'investments.upload_data_chart': 'Subir Datos',
    'investments.dynamic_chart': 'Gráficos de Imágenes de Gráfico Dinámico',
    'investments.portfolio_allocation': 'Asignación de Cartera',
    'investments.current_asset_distribution': 'Distribución actual de activos',
    'investments.stocks': 'Acciones',
    'investments.bonds': 'Bonos',
    'investments.cash': 'Efectivo',
    'investments.recent_performance': 'Rendimiento Reciente',
    'investments.last_30_days_performance': 'Rendimiento de los últimos 30 días',
    'investments.portfolio': 'Cartera',
    'investments.image_gallery': 'Galería de Imágenes',
    'investments.images': 'Imágenes',
    'investments.charts': 'Gráficos',
    // Client schedule translations
    'schedule.title': 'Programar',
    'schedule.description': 'Gestiona tus reuniones y citas con tu equipo financiero.',
    'schedule.schedule_meeting': 'Programar Reunión',
    'schedule.upcoming': 'Próximas',
    'schedule.this_month': 'Este Mes',
    'schedule.completed': 'Completadas',
    'schedule.meetings_scheduled': 'Reuniones programadas',
    'schedule.december_2024': 'Diciembre 2024',
    'schedule.total_meetings': 'Total de reuniones',
    'schedule.new_meeting': 'Programar Nueva Reunión',
    'schedule.create_meeting': 'Crear una nueva reunión con tu asesor financiero',
    'schedule.meeting_title': 'Título de la Reunión',
    'schedule.date': 'Fecha',
    'schedule.time': 'Hora',
    'schedule.meeting_type': 'Tipo de Reunión',
    'schedule.video_call': 'Llamada de Video',
    'schedule.in_person': 'En Persona',
    'schedule.phone_call': 'Llamada Telefónica',
    'schedule.notes_optional': 'Notas (Opcional)',
    'schedule.any_additional_notes': 'Cualquier nota adicional o elementos de agenda...',
    'schedule.cancel': 'Cancelar',
    'schedule.upcoming_meetings': 'Reuniones Próximas',
    'schedule.scheduled_meetings': 'Tus reuniones y citas programadas',
    'schedule.meeting_history': 'Historial de Reuniones',
    'schedule.completed_meetings': 'Tus reuniones y citas completadas',
    'schedule.no_upcoming_meetings': 'No hay reuniones próximas',
    'schedule.schedule_meeting_to_start': 'Programa una reunión para comenzar.',
    'schedule.no_completed_meetings': 'No hay reuniones completadas',
    'schedule.meeting_history_will_appear': 'Tu historial de reuniones aparecerá aquí.',
    'client.dashboard.refresh': 'Actualizar',
    'client.dashboard.export': 'Exportar',
    'client.dashboard.withdraw': 'Retirar',
    'client.dashboard.new_payment': 'Nuevo Pago',
    'client.dashboard.available_balance': 'Saldo Disponible',
    'client.dashboard.total_invested': 'Total Invertido',
    'client.dashboard.monthly_return': 'Retorno Mensual',
    'client.dashboard.active_investments': 'Inversiones Activas',
    'client.dashboard.notifications': 'Notificaciones',
    'client.dashboard.new_alerts': 'Nuevas alertas',
    'client.dashboard.new_this_week': 'nuevos esta semana',
    'client.dashboard.unread': 'sin leer',
    'client.dashboard.from_last_month': 'del mes pasado',
    'client.dashboard.investment_analytics': 'Análisis de Inversiones',
    'client.dashboard.visualize_portfolio': 'Visualiza el rendimiento de tu cartera y asignación de activos',
    'client.dashboard.portfolio_performance': 'Rendimiento de Cartera',
    'client.dashboard.asset_allocation': 'Asignación de Activos',
    'client.dashboard.monthly_returns': 'Retornos Mensuales',
    'client.dashboard.interactive_chart': 'Visualización de gráfico interactivo',
    'client.dashboard.portfolio_value': 'Valor de Cartera',
    'client.dashboard.best_month': 'Mejor Mes',
    'client.dashboard.worst_month': 'Peor Mes',
    'client.dashboard.current_value': 'Valor Actual',
    'client.dashboard.return': 'retorno',
    // Demo login translations
    'demo.mode.title': 'Modo Demo',
    'demo.mode.description': 'Haz clic en los botones de abajo para probar diferentes tipos de usuario:',
    'demo.admin.title': 'Panel de Administración',
    'demo.admin.description': 'Accede al panel de administración con capacidades de gestión completas:',
    'demo.admin.feature1': 'Gestionar todos los clientes y sus cuentas',
    'demo.admin.feature2': 'Ver análisis y reportes del sistema',
    'demo.admin.feature3': 'Acceder a controles de procesamiento de pagos',
    'demo.admin.feature4': 'Monitorear actividad de usuarios y mensajes',
    'demo.admin.feature5': 'Configuración y ajustes del sistema',
    'demo.admin.button': 'Iniciar como Admin',
    'demo.admin.user_name': 'Usuario Admin',
    'demo.client.title': 'Portal del Cliente',
    'demo.client.description': 'Experimenta el panel del cliente con características personales:',
    'demo.client.feature1': 'Ver saldo de cuenta y transacciones',
    'demo.client.feature2': 'Realizar pagos y retiros',
    'demo.client.feature3': 'Acceder a reportes de inversión y gráficos',
    'demo.client.feature4': 'Comunicarse con el equipo de soporte',
    'demo.client.feature5': 'Gestionar documentos y archivos personales',
    'demo.client.button': 'Iniciar como Cliente',
    'demo.client.user_name': 'Usuario Cliente',
    'demo.note.title': 'Nota:',
    'demo.note.description': 'Ambas cuentas demo usan datos simulados. En una aplicación real, estas serían cuentas de usuario reales con datos y permisos reales.',
    'demo.email.title': 'Autenticación por Email',
    'demo.email.description': 'También puedes probar el flujo de autenticación usando estas direcciones de email demo:',
    'demo.email.admin': 'Panel de Administración',
    'demo.email.client': 'Portal del Cliente',
    'demo.email.instruction': 'Ingresa cualquiera de los emails de arriba y haz clic en "Enviar Enlace Mágico" para probar el flujo completo de autenticación.',
    // Navigation translations
    'nav.features': 'Características',
    'nav.pricing': 'Precios',
    'nav.contact': 'Contacto',
    // Client chat translations
    'client.chat.schedule_call': 'Programar Llamada',
    'client.chat.schedule_call_desc': 'Reserva una consulta telefónica con tu asesor',
    'client.chat.video_meeting': 'Reunión por Video',
    'client.chat.video_meeting_desc': 'Inicia una videollamada con tu equipo',
    'client.chat.send_email': 'Enviar Email',
    'client.chat.send_email_desc': 'Envía un mensaje detallado por email',
    'client.chat.need_assistance': '¿Necesitas Asistencia Inmediata?',
    'client.chat.support_available': 'Nuestro equipo de soporte está disponible 24/7 para asuntos urgentes.',
    'client.chat.call_now': 'Llamar Ahora',
    'client.chat.email': 'Email',
    // Client payments translations
    'client.payments.need_help': '¿Necesitas Ayuda con los Pagos?',
    'client.payments.contact_support_desc': 'Contacta a nuestro equipo de soporte para asistencia con el procesamiento de pagos.',
    'client.payments.contact_support': 'Contactar Soporte',
    // Client footer translations
    'client.footer.description': 'Tu puerta de entrada segura para gestionar tu cuenta, ver documentos y comunicarte con nuestro equipo.',
    'client.footer.email': 'Email',
    'client.footer.call': 'Llamar',
    'client.footer.quick_links': 'Enlaces Rápidos',
    'client.footer.dashboard': 'Panel',
    'client.footer.documents': 'Documentos',
    'client.footer.messages': 'Mensajes',
    'client.footer.billing': 'Facturación',
    'client.footer.support': 'Soporte',
    'client.footer.help_center': 'Centro de Ayuda',
    'client.footer.live_chat': 'Chat en Vivo',
    'client.footer.contact_support': 'Contactar Soporte',
    'client.footer.faq': 'Preguntas Frecuentes',
    'client.footer.contact_us': 'Contáctanos',
    'client.footer.live_chat_available': 'Chat en Vivo Disponible',
    'client.footer.all_rights_reserved': 'Portal del Cliente. Todos los derechos reservados.',
    'client.footer.privacy_policy': 'Política de Privacidad',
    'client.footer.terms_of_service': 'Términos de Servicio',
    'client.footer.made_with': 'Hecho con',
    'client.footer.for_our_clients': 'para nuestros clientes',
    // Gallery translations
    'gallery.upload': 'Subir',
    'gallery.uploading': 'Subiendo...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');
  const [isInitialized, setIsInitialized] = useState(false);
  const [renderKey, setRenderKey] = useState(0);

  useEffect(() => {
    // Get language from localStorage or default to Spanish
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    } else {
      // Set default to Spanish if no saved language
      setLanguage('es');
    }
    setIsInitialized(true);
  }, []);

  const handleSetLanguage = (newLanguage: Language) => {
    console.log('Setting language to:', newLanguage);
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
    // Force re-render by updating the render key
    setRenderKey(prev => prev + 1);
    
    // Dispatch a custom event to notify all components
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('languageChanged', { 
        detail: { language: newLanguage } 
      }));
      
      // Also dispatch a storage event to trigger re-renders
      window.dispatchEvent(new StorageEvent('storage', {
        key: 'language',
        newValue: newLanguage,
        oldValue: language,
        storageArea: localStorage
      }));
    }
  };

  const t = (key: string): string => {
    try {
      // Use the current language setting
      const currentTranslation = translations[language][key as keyof typeof translations[typeof language]];
      if (currentTranslation) {
        return currentTranslation;
      }
      
      // Fallback to Spanish if translation not found
      const spanishTranslation = translations['es'][key as keyof typeof translations['es']];
      if (spanishTranslation) {
        return spanishTranslation;
      }
      
      // Fallback to key if translation not found
      console.warn('Translation not found for key:', key, 'for language:', language);
      return key;
    } catch (error) {
      console.error('Translation error for key:', key, 'for language:', language, error);
      return key;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      <div key={renderKey}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }

  // Force re-render when language changes by using the renderKey
  const [, forceUpdate] = useState({});
  
  useEffect(() => {
    const handleLanguageChange = () => {
      forceUpdate({});
    };
    
    if (typeof window !== 'undefined') {
      window.addEventListener('languageChanged', handleLanguageChange);
      return () => {
        window.removeEventListener('languageChanged', handleLanguageChange);
      };
    }
  }, []);

  return context;
}

// Hook for components that need to re-render on language change but don't use translations
export function useLanguageChange() {
  const [language, setLanguage] = useState<Language>('es');
  
  useEffect(() => {
    // Get initial language
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
    
    // Listen for language changes
    const handleLanguageChange = (event: CustomEvent) => {
      console.log('Language change event received:', event.detail.language);
      setLanguage(event.detail.language);
    };
    
    // Listen for storage changes
    const handleStorageChange = (event: StorageEvent) => {
      if (event.key === 'language' && event.newValue) {
        console.log('Language storage change event received:', event.newValue);
        setLanguage(event.newValue as Language);
      }
    };
    
    if (typeof window !== 'undefined') {
      window.addEventListener('languageChanged', handleLanguageChange as EventListener);
      window.addEventListener('storage', handleStorageChange);
      return () => {
        window.removeEventListener('languageChanged', handleLanguageChange as EventListener);
        window.removeEventListener('storage', handleStorageChange);
      };
    }
  }, []);
  
  return language;
}